# Generated by Django 3.2.16 on 2023-06-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_pagos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='fecha_expiracion',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='anio_expiracion',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='mes_expiracion',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='dni_titular',
            field=models.CharField(max_length=16),
        ),
    ]
