# Generated by Django 3.2.16 on 2023-06-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_pagos', '0002_auto_20230627_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='dni_titular',
            field=models.CharField(max_length=8),
        ),
    ]
