# Generated by Django 3.2.16 on 2023-07-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_pagos', '0003_alter_tarjeta_dni_titular'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='saldo',
            field=models.FloatField(default=0, null=True),
        ),
    ]
