# Generated by Django 3.2.16 on 2023-05-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_turnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franja_horaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franja', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'franja_horaria',
                'verbose_name_plural': 'franjas_horarias',
            },
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='turno',
            name='franja_horaria',
        ),
        migrations.AddField(
            model_name='turno',
            name='franja_horaria',
            field=models.ManyToManyField(to='gestion_de_turnos.Franja_horaria'),
        ),
    ]
