# Generated by Django 3.2.16 on 2023-05-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_turnos', '0002_auto_20230512_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='franja_horaria',
        ),
        migrations.AddField(
            model_name='turno',
            name='franja_horaria',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
