# Generated by Django 3.2.16 on 2023-05-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_turnos', '0003_auto_20230512_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('franja_horaria', 'fecha')},
        ),
    ]
