# Generated by Django 3.2.16 on 2023-05-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_turnos', '0004_auto_20230512_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(blank=True, default='Pendiente', max_length=50),
        ),
    ]
