# Generated by Django 3.2.16 on 2023-05-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_turnos', '0006_turno_dni_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='dni_creator',
            field=models.CharField(max_length=8),
        ),
    ]
