# Generated by Django 3.2.16 on 2023-05-21 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_de_turnos', '0007_alter_turno_dni_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='dni_creator',
        ),
        migrations.AddField(
            model_name='turno',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
