# Generated by Django 3.2.16 on 2023-07-05 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_servicios_prestados', '0009_servicio_veterinario'),
        ('gestion_de_turnos', '0009_alter_turno_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_de_servicios_prestados.servicio_veterinario'),
        ),
    ]
