# Generated by Django 3.2.16 on 2023-07-05 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0050_auto_20230704_1327'),
        ('gestion_de_turnos', '0010_alter_turno_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='perro',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion_de_mascotas.perro'),
        ),
    ]
