# Generated by Django 3.2.16 on 2023-07-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0064_remove_perro_perdido_nueva_imagen'),
        ('gestion_de_turnos', '0014_alter_turno_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('franja_horaria', 'fecha', 'perro')},
        ),
    ]
