# Generated by Django 3.2.16 on 2023-04-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_servicios_prestados', '0002_auto_20230428_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='paseador',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
