# Generated by Django 3.2.16 on 2023-05-18 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_servicios_prestados', '0003_auto_20230428_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuidador',
            old_name='zona',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='paseador',
            old_name='zona',
            new_name='descripcion',
        ),
    ]
