# Generated by Django 3.2.16 on 2023-06-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_servicios_prestados', '0007_auto_20230518_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidador',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paseador',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
