# Generated by Django 3.2.16 on 2023-07-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campania_de_donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Nombre')),
                ('monto_esperado', models.FloatField()),
            ],
            options={
                'verbose_name': 'campaña_de_donacion',
                'verbose_name_plural': 'campañas_de_donaciones',
                'unique_together': {('titulo', 'monto_esperado')},
            },
        ),
    ]
