# Generated by Django 3.2.16 on 2023-07-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_donaciones', '0003_solicitud_donacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='campania_de_donacion',
            name='monto_actual',
            field=models.FloatField(default=0, null=True),
        ),
    ]
