# Generated by Django 3.2.16 on 2023-07-09 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_donaciones', '0005_donacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='campania_de_donacion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_de_donaciones.campania_de_donacion'),
        ),
    ]
