# Generated by Django 3.2.16 on 2023-04-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perro_encontrado',
            options={'verbose_name': 'perro_encontrado', 'verbose_name_plural': 'perros_encontrados'},
        ),
        migrations.AlterModelOptions(
            name='perro_perdido',
            options={'verbose_name': 'perro_perdido', 'verbose_name_plural': 'perros_perdidos'},
        ),
        migrations.AlterField(
            model_name='perro_encontrado',
            name='imagen',
            field=models.ImageField(upload_to='perros_encontrados'),
        ),
        migrations.AlterField(
            model_name='perro_perdido',
            name='imagen',
            field=models.ImageField(null=True, upload_to='perros_perdidos'),
        ),
    ]
