# Generated by Django 3.2.16 on 2023-04-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0004_remove_perro_perdido_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('dni_owner', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'perro',
                'verbose_name_plural': 'perros',
                'unique_together': {('nombre', 'dni_owner')},
            },
        ),
    ]
