# Generated by Django 3.2.16 on 2023-05-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0006_perro_en_adopcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro_encontrado',
            name='created_by',
            field=models.CharField(default=None, max_length=8),
            preserve_default=False,
        ),
    ]
