# Generated by Django 3.2.16 on 2023-05-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0008_perro_perdido_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro_en_adopcion',
            name='created_by',
            field=models.CharField(default=None, max_length=8),
            preserve_default=False,
        ),
    ]
