# Generated by Django 3.2.16 on 2023-05-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0009_perro_en_adopcion_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro_en_adopcion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='perro_en_adopcion',
            name='localidad',
        ),
        migrations.AddField(
            model_name='perro_en_adopcion',
            name='detalles_de_salud',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='perro_en_adopcion',
            name='historia',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='perro_en_adopcion',
            name='tamanio',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='perro_en_adopcion',
            name='titulo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='perro_en_adopcion',
            name='zona',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perro_en_adopcion',
            name='edad',
            field=models.CharField(max_length=30),
        ),
    ]
