# Generated by Django 3.2.16 on 2023-05-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0014_auto_20230521_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='edad',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='perro',
            name='peso',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='perro',
            name='size',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='dni_owner',
            field=models.CharField(default=None, max_length=8, null=True, verbose_name='Dni del dueño'),
        ),
    ]
