# Generated by Django 3.2.16 on 2023-05-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0017_auto_20230525_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro_en_adopcion',
            name='adoptado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perro',
            name='edad',
            field=models.IntegerField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='peso',
            field=models.FloatField(verbose_name='Peso'),
        ),
    ]
