# Generated by Django 3.2.16 on 2023-05-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0018_auto_20230525_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro_encontrado',
            name='telefono',
        ),
        migrations.AddField(
            model_name='perro_encontrado',
            name='fecha_encontrado',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='perro_encontrado',
            name='size',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='perro_encontrado',
            name='zona',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
