# Generated by Django 3.2.16 on 2023-05-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0019_auto_20230526_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro_encontrado',
            name='fecha_encontrado',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='perro_encontrado',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='perro_encontrado',
            name='zona',
            field=models.CharField(max_length=100),
        ),
    ]
