# Generated by Django 3.2.16 on 2023-05-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0021_alter_perro_encontrado_fecha_encontrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro_perdido',
            name='telefono',
        ),
        migrations.AddField(
            model_name='perro_perdido',
            name='edad',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='perro_perdido',
            name='fecha_encontrado',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='perro_perdido',
            name='size',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='perro_perdido',
            name='zona',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
