# Generated by Django 3.2.16 on 2023-05-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0022_auto_20230526_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro_perdido',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='perro_perdido',
            name='fecha_encontrado',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='perro_perdido',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='perro_perdido',
            name='zona',
            field=models.CharField(max_length=100),
        ),
    ]
