# Generated by Django 3.2.16 on 2023-05-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0023_auto_20230526_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perro_perdido',
            old_name='fecha_encontrado',
            new_name='fecha_perdido',
        ),
    ]
