# Generated by Django 3.2.16 on 2023-05-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0024_rename_fecha_encontrado_perro_perdido_fecha_perdido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='edad',
            field=models.CharField(max_length=100, verbose_name='Edad'),
        ),
    ]
