# Generated by Django 3.2.16 on 2023-06-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0025_alter_perro_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro_perdido',
            name='edad',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
