# Generated by Django 3.2.16 on 2023-06-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0027_alter_perro_perdido_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='nacimiento',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='perro',
            name='raza',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perro',
            name='sexo',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
