# Generated by Django 3.2.16 on 2023-06-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0030_auto_20230609_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='edad',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Edad'),
        ),
    ]
