# Generated by Django 3.2.16 on 2023-06-09 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0031_alter_perro_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='edad',
        ),
    ]
