# Generated by Django 3.2.16 on 2023-06-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0032_remove_perro_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro_perdido',
            name='franja_horaria',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perro_perdido',
            name='sexo',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
