# Generated by Django 3.2.16 on 2023-06-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0035_perro_perdido_raza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro_perdido',
            name='raza',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
