# Generated by Django 3.2.16 on 2023-06-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0037_alter_perro_perdido_raza'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro_perdido',
            name='encontrado',
            field=models.BooleanField(default=False),
        ),
    ]
