# Generated by Django 3.2.16 on 2023-06-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0039_auto_20230610_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro_encontrado',
            name='edad',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perro_encontrado',
            name='franja_horaria',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perro_encontrado',
            name='raza',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perro_encontrado',
            name='recuperado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perro_encontrado',
            name='sexo',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perro_encontrado',
            name='titulo',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
