# Generated by Django 3.2.16 on 2023-06-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0040_auto_20230610_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro_en_adopcion',
            name='sexo',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
