# Generated by Django 3.2.16 on 2023-06-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0041_perro_en_adopcion_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='peso',
        ),
    ]
