# Generated by Django 3.2.16 on 2023-06-27 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_de_mascotas', '0042_remove_perro_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='perro',
            unique_together={('nombre', 'owner')},
        ),
        migrations.RemoveField(
            model_name='perro',
            name='dni_owner',
        ),
    ]
