# Generated by Django 3.2.16 on 2023-06-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0043_auto_20230627_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
            },
        ),
        migrations.RemoveField(
            model_name='perro',
            name='raza',
        ),
        migrations.AddField(
            model_name='perro',
            name='raza',
            field=models.ManyToManyField(to='gestion_de_mascotas.Raza'),
        ),
    ]
