# Generated by Django 3.2.16 on 2023-06-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0044_auto_20230628_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raza',
            old_name='raza',
            new_name='nombre',
        ),
    ]
