# Generated by Django 3.2.16 on 2023-07-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0047_alter_perro_raza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('peso', models.FloatField()),
                ('motivo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('seguimiento', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'entrada',
                'verbose_name_plural': 'entradas',
            },
        ),
    ]
