# Generated by Django 3.2.16 on 2023-07-04 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0049_entrada_perro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro_encontrado',
            name='raza',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_de_mascotas.raza'),
        ),
        migrations.AlterField(
            model_name='perro_perdido',
            name='raza',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_de_mascotas.raza'),
        ),
    ]
