# Generated by Django 3.2.16 on 2023-07-06 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_servicios_prestados', '0009_servicio_veterinario'),
        ('gestion_de_mascotas', '0050_auto_20230704_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_servicios_prestados.servicio_veterinario'),
        ),
    ]
