# Generated by Django 3.2.16 on 2023-07-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0054_auto_20230708_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacuna',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='perro',
        ),
    ]
