# Generated by Django 3.2.16 on 2023-07-08 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0056_auto_20230708_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('numero_dosis', models.PositiveIntegerField()),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_mascotas.perro')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_mascotas.vacuna')),
            ],
            options={
                'verbose_name': 'registro_vacuna',
                'verbose_name_plural': 'registros_vacunas',
            },
        ),
    ]
