# Generated by Django 3.2.16 on 2023-07-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0058_alter_entrada_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='numero_dosis',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
