# Generated by Django 3.2.16 on 2023-07-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0059_alter_entrada_numero_dosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='numero_dosis',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
