# Generated by Django 3.2.16 on 2023-07-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_mascotas', '0061_registro_vacuna_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='libreta_sanitaria',
            name='anteultima_desparasitacion',
            field=models.DateField(null=True),
        ),
    ]
